### ISSUE TITLE
Datasets download issue

### ISSUE THREAD

**Issue by robo-boluo** [uds-lsv/llmft#4]
when run the experiments model, I can download part of the data before encountering the TypeError notice on Collab. Notice 

''

_Traceback (most recent call last):
  File "/content/drive/MyDrive/llmft/ft.py", line 711, in <module>
    main()
  File "/content/drive/MyDrive/llmft/ft.py", line 150, in main
    raw_datasets, label_list, num_labels, is_regression = load_glue_datasets(
  File "/content/drive/MyDrive/llmft/task_utils.py", line 138, in load_glue_datasets
    raw_datasets = load_dataset(_

......

**Comment by robo-boluo** [comment]
This issue has been solved by updating datasets and deepspeed before starting a experiment test:

!pip install --upgrade datasets
! pip uninstall -y deepspeed
! DS_BUILD_CUDA_VERSION=12.2 pip install deepspeed
